import { environment } from "../environments/environment";

 

const APIStandars = {

    //guest APIs
    loginAPI : environment.baseUrl  +  "auth/login",
    schoolRegisterAPI: environment.baseUrl + "auth/register",
    countriesAPI: "https://places-xchange.glitch.me/getCountries",
    satateAPI: "https://places-xchange.glitch.me/getStates",
    getUserDetails: environment.baseUrl + "auth/getUserDetails",
    uploadProfilePic: environment.baseUrl + "auth/uploadProfilePic",
    updatePassword: environment.baseUrl + "auth/updatePassword",
    forgetPassword: environment.baseUrl+ "auth/forgetPassword",
    reset_password: environment.baseUrl+ "auth/reset_password",
    classCodeVerify: environment.baseUrl+ "auth/classCodeVerify",
    generateOTP: environment.baseUrl + "auth/generateOTP",
    verifyEmail: environment.baseUrl + "auth/verifyEmail",
    studentSelfReg: environment.baseUrl + "auth/studentSelfReg",
    guest: {
      sendFeedback: environment.baseUrl + "auth/sendFeedbackData"
    },

    //School APIs
    addParentAPI: environment.baseUrl  +  "school/addParent",
    listOfParents: environment.baseUrl + "school/listParent",
    addStudentAPI: environment.baseUrl  +  "school/addStudent",
    listStudentAPI: environment.baseUrl  +  "school/listStudent",
    listTeacherAPI:  environment.baseUrl  +  "school/listTeacher",
    addTeacher:  environment.baseUrl  +  "school/addTeacher",
    listStaffAPI:  environment.baseUrl  +  "school/listStaff",
    addStaff:  environment.baseUrl  +  "school/addStaff",
    addStandardAPI: environment.baseUrl + "school/addStandard",
    listStandardAPI: environment.baseUrl + "school/listStandard",
    addDivisionAPI: environment.baseUrl + "school/addDivision",
    listDivisionAPI: environment.baseUrl + "school/listDivision",
    addSubjectAPI: environment.baseUrl + "school/addSubject",
    listSubjectAPI: environment.baseUrl + "school/listSubject",
    mapStudentsAPI: environment.baseUrl + "school/assignStudent",
    mapTeachersAPI: environment.baseUrl + "school/assignTeacher",
    listStudentMap: environment.baseUrl + "school/listAssignStudent",
    listTeacherMap: environment.baseUrl + "school/listAssignTeacher",
    assignDigitalSkillMentorForSchoolAPI: environment.baseUrl + "school/assignDigitalMentor",
    listDigitalSkillMentorForSchoolAPI: environment.baseUrl + "school/listDigitalMentor",
    assignMentorTeachers: environment.baseUrl + "school/assignMentorTeacher",
    listAssignMentorTeachers: environment.baseUrl + "school/listAssignMentorTeacher",
    getSchoolDetails: environment.baseUrl + "school/getSchoolDetails",
    assignSectionHead: environment.baseUrl + "school/assignSectionHeads",
    sectionHeadLists: environment.baseUrl + "school/listSectionHeads",
    totalCounts: environment.baseUrl + "school/totalCount",
    school:{
        classTeacherList: environment.baseUrl + "school/listClassTeacher",
        assignClassTeacher: environment.baseUrl + "school/assignClassTeacher",
        listAssignTeacher:environment.baseUrl + "school/listAssignTeacher",
    },
    addEvent : environment.baseUrl + "school/addEvent",
    getEvent : environment.baseUrl + "school/getEvent",
    assignHoD : environment.baseUrl + "school/assignHoD",
    listHod : environment.baseUrl + "school/listHod",
    switchOffClass:environment.baseUrl + "school/switchOffClass",
    listOffClass:environment.baseUrl + "school/listOffClass",
    switchBack:environment.baseUrl + "school/switchBack",
    listAssignStudent:environment.baseUrl + "school/listAssignStudent",
    premotion:environment.baseUrl + "school/premotion",
    listSections:environment.baseUrl + "school/listSections",
    listmapSection:environment.baseUrl + "school/listmapSection",
    mapSections:environment.baseUrl + "school/mapSections",

    //teacher APIs
    listSubjectForTeacher: environment.baseUrl + "teacher/listSubjects",
    addLesson: environment.baseUrl + "teacher/addLesson",
    listLessonsForTeachers: environment.baseUrl + "teacher/listLessons",
    getLessonForTeachers: environment.baseUrl + "teacher/getLessonDetails",
    addContentForTeachersAPI: environment.baseUrl + "teacher/addContent",
    getParentInfoTeacherAPI: environment.baseUrl + "teacher/getparentinfo",
    addSupportLessonAPI: environment.baseUrl + "teacher/addSupportLesson",
    getSupportContentsTeacherAPI: environment.baseUrl + "teacher/getSupportLessons",
    listContentTeacherAPI: environment.baseUrl + "teacher/listContent",
    deleteLessonContentTeacherAPI: environment.baseUrl + "teacher/deleteLessonContent",
    fileFetchTeachersAPI: environment.baseUrl + "teacher/fileFetch",
    getOverviewMarksReportForTeacher: environment.baseUrl + "teacher/getStudentReports",
    getDetailedStudentAnswersForTeacherAPI: environment.baseUrl + "teacher/getQ&AReport",
    listDigitalSkillClassesForTeacherAPI: environment.baseUrl + "teacher/listAssignDigitalClass",
    listDigitalSkillsForTeacherAPI: environment.baseUrl + "teacher/listDigitalLesson",
    listDigitalSkillAssignmentSubmissionsForTeacherAPI: environment.baseUrl + "teacher/getStudentDigitalContent",
    reviewAssignmentForTeacherAPI: environment.baseUrl + "teacher/reviewDigitalAssignment",
    getAssignemntSubmissionStatusForTeacherAPI: environment.baseUrl + "teacher/getAssignmentSubmissionStatus",
    listDigitalSkillContentForTeacherAPI: environment.baseUrl + "teacher/listDigitalContent",  
    submitDigitalSkillContentForTeacherAPI: environment.baseUrl + "teacher/submitDigitalSkill",
    getAssignmentStatusForTeacherAPI: environment.baseUrl + "teacher/getAssignmentSubmissionStatusByTeacher",
    preAssesmentDashboardReportForTeacherAPI: environment.baseUrl + "teacher/Pre_assessmentDashboardReport",
    postAssesmentDashboardReportForTeacherAPI: environment.baseUrl + "teacher/post_assessmentDashboardReport",
    selfAssesmentDashboardReportForTeacherAPI: environment.baseUrl + "teacher/self_DashboardReport",
    getStudentsCountForTeacherAPI: environment.baseUrl + "teacher/getStudentsCount",
    publishLesson: environment.baseUrl + "teacher/publishLesson",
    migrateLesson: environment.baseUrl + "teacher/shareChapter",
    getTeacherDetails: environment.baseUrl + "teacher/teacherDetails",
    checkIfSectionHead:environment.baseUrl + "sectionHead/checkIfSectionHead",
    getLessonPlanCountForTeacherAPI: environment.baseUrl + "teacher/getLessonPlanCount",
    teacher:{
        listActivities: environment.baseUrl + "teacher/getActivitys"
    },
    sectionHead:{
        listClasses: environment.baseUrl + "sectionHead/listClasses",
        listSubjectTeacher: environment.baseUrl + "sectionHead/listSubjectTeacher",
        listLessons: environment.baseUrl + "sectionHead/listLessons",
        getSupportLesson: environment.baseUrl + "sectionHead/getSupportLesson",
        listContent: environment.baseUrl + "sectionHead/listContent",
        
    },
    classTeacher:{
        listSubject:  environment.baseUrl + "classTeacher/listSubject",
        checkIfClassTeacher: environment.baseUrl + "classTeacher/checkIfClassTeacher",
        subjectProgress: environment.baseUrl + "classTeacher/subjectProgress",
        listStudents:environment.baseUrl + "classTeacher/listStudents",
        removeStudent:environment.baseUrl + "classTeacher/removeStudent",
    },
    HOD:{
        checkIfHOD: environment.baseUrl + "hod/checkIfHOD",
        listTeachers: environment.baseUrl + "hod/listTeachers",
        listClass: environment.baseUrl + "hod/listClass",
        listLessons: environment.baseUrl + "hod/listLessons",
        getSupportLesson: environment.baseUrl + "hod/getSupportLesson",
        listContent: environment.baseUrl + "hod/listContent",
        reviewLesson:environment.baseUrl + "hod/reviewLesson",
        ifReviewed:environment.baseUrl + "hod/ifReviewed",
        listUnitWithChapterTeacher:environment.baseUrl + "hod/listUnitWithChapter",
        listPreviewTopicsHOD:environment.baseUrl + "hod/listPreviewTopics",
        listPreviewConceptsHOD:environment.baseUrl + "hod/listPreviewConcepts",
    },
    getTeacherEvent: environment.baseUrl + "teacher/getEvent",
    completedChapter: environment.baseUrl + "teacher/completedChapter",
    notificationEvents: environment.baseUrl + "teacher/notificationEvents",
    listMicroAndNano: environment.baseUrl + "teacher/listMicroAndNano",
    

    microActivityStatus : environment.baseUrl + "teacher/microActivityStatus",
    lessonComplition : environment.baseUrl + "teacher/lessonComplition",
    getLessonCompletion : environment.baseUrl + "teacher/getLessonCompletion",
    ifTotalLessonAdded : environment.baseUrl + "teacher/ifTotalLessonAdded",
    addTotalLessonCount : environment.baseUrl + "teacher/addTotalLessonCount",
    teachingCompletion : environment.baseUrl + "teacher/teachingCompletion",
    getLessonScore : environment.baseUrl + "teacher/getLessonScore",
    microLessonCompletion : environment.baseUrl + "teacher/microLessonCompletion",
    studentCompletionOnTime : environment.baseUrl + "teacher/studentCompletionOnTime",
    findMyProgress : environment.baseUrl + "teacher/findMyProgress",
    getLessonPreprationScore: environment.baseUrl + "teacher/getLessonPreprationScore",
    logTeachingStart:environment.baseUrl + "teacher/logTeachingStart",
    getQuotes:environment.baseUrl + "teacher/getQuotes",

    listteacherLabChapters: environment.baseUrl + "teacher/listLabChapters",
    listteachertInventory: environment.baseUrl + "teacher/listInventory",
    listTeacherInventoryContent: environment.baseUrl + "teacher/listInventoryContent",
    playVideo: environment.baseUrl + "teacher/playVedio",
    getTeacherViewCount: environment.baseUrl + "teacher/getViewCount",
    getTeacherInventoryData: environment.baseUrl + "teacher/getInventoryData",
    completedTeacherInventory: environment.baseUrl + "teacher/completedInventory",
    taskTeacherSubmission: environment.baseUrl + "teacher/taskSubmission",
    listChallange: environment.baseUrl + "teacher/listChallange",
    listTeacherTask:environment.baseUrl + "teacher/listTask",
    ifLabMentor:environment.baseUrl + "teacher/ifLabMentor",
    findCompletedTeacherTask:environment.baseUrl + "teacher/findCompletedTask",
    getInventoryTeacherData:environment.baseUrl + "teacher/getInventoryData",
    listMentorClass:environment.baseUrl + "teacher/listMentorClass",
    liststudentSubmissionsReport:environment.baseUrl + "teacher/liststudentSubmissionsReport",
    listChallengeAndTask:environment.baseUrl + "teacher/listChallengeAndTask",
    liststudSubmissions:environment.baseUrl + "teacher/liststudSubmissions",
    reviewLabTask:environment.baseUrl + "teacher/reviewLabTask",
    reviewActivity:environment.baseUrl + "teacher/reviewActivity",
    listLessonContentForTeacherAPI: environment.baseUrl + "teacher/listContent",
    listUnit:environment.baseUrl + "teacher/listUnit",
    createUnit:environment.baseUrl + "teacher/createUnit",
    listChapterinUnit:environment.baseUrl + "teacher/listChapterinUnit",
    listConcept:environment.baseUrl + "teacher/listConcept",
    listPreviewConcepts:environment.baseUrl + "teacher/listPreviewConcepts",
    getUnitDetails:environment.baseUrl + "teacher/getUnitDetails",
    listPreviewTopics:environment.baseUrl + "teacher/listPreviewTopics",
    deleteUnit:environment.baseUrl + "teacher/deleteUnit",
    shareChaptertoUnit:environment.baseUrl + "teacher/shareChaptertoUnit",
    deleteChapter:environment.baseUrl + "teacher/deleteChapter",
    listOwnBatch: environment.baseUrl + "teacher/listOwnBatch",
    listBatchModules: environment.baseUrl + "teacher/listBatchModules",
    mapLabLesson: environment.baseUrl + "teacher/mapLabLesson",
    listBatchAPI: environment.baseUrl + "teacher/listBatch",
    enterBatch: environment.baseUrl + "teacher/enterBatch",
    joinedUseCode: environment.baseUrl + "teacher/joinedUseCode",
    updateMode: environment.baseUrl + "teacher/updateMode",
    listTaskwithStudentTask: environment.baseUrl + "teacher/listTaskwithStudentTask",
    listTeacherForShare:environment.baseUrl + "teacher/listTeacherForShare",
    listShareClass: environment.baseUrl + "teacher/listShareClass",
    shareChapter:environment.baseUrl + "teacher/shareChapter",

    //Student Apis
    
    getLessonForStudentAPI: environment.baseUrl + "student/listLesson",
    getSupportContentsStudentAPI: environment.baseUrl + "student/getSupportLessons",
    getAssesmentsForChapter: environment.baseUrl + "student/getAssesmentQuestionsForChapter",
    getChildLessonsForStudentAPI: environment.baseUrl + "student/getChildLessons",
    checkPreAssessmentForStudent: environment.baseUrl + "student/checkPreAssessment",
    addContentForStudent: environment.baseUrl + "student/addStudentContent",
    getSubjectsForStudentAPI: environment.baseUrl + "student/listSubject",
    checkMicroUnitCompletedForStudent: environment.baseUrl + "student/checkMicroUnitCompleted",
    checkPostAssessmentForStudent: environment.baseUrl + "student/checkPostAssessment",
    getStudentContentsForStudentAPI: environment.baseUrl + "student/getStudentContents",
    listLessonContentForStudentAPI: environment.baseUrl + "student/listContent",
    getStudentReportForStudentAPI: environment.baseUrl + "student/getMyReports",
    listDigitalSkillsForStudentAPI: environment.baseUrl + "student/listDigitalsLessons",
    listDigitalSkillContentForStudentAPI: environment.baseUrl + "student/listDigitalsContents",
    submitDigitalSkillContentForStudentAPI: environment.baseUrl + "student/submitDigitalsContent",
    getAssignmtnStatusForStudentAPI: environment.baseUrl + "student/assignmentStatus",
    student: {
        assesmentPreview:  environment.baseUrl + "student/pre_postResultView",
        listOutcomes: environment.baseUrl + "student/listOutcome"
    },
    getStudentEvent: environment.baseUrl + "student/getEvent",
    listLabChapters: environment.baseUrl + "student/listLabChapters",
    listStudentInventory:environment.baseUrl + "student/listInventory",
    listStudentInventoryContent:environment.baseUrl + "student/listInventoryContent",
    playVedio:environment.baseUrl + "student/playVedio",
    getViewCount:environment.baseUrl + "student/getViewCount",
    getInventoryData:environment.baseUrl + "student/getInventoryData",
    completedInventory: environment.baseUrl + "student/completedInventory",
    getQuotesStudent:environment.baseUrl + "student/getQuotes",
    listStudentTask:environment.baseUrl + "student/listTask",
    taskSubmission:environment.baseUrl + "student/taskSubmission",
    findCompletedTask:environment.baseUrl + "student/findCompletedTask",
    listMicroAndNanounit: environment.baseUrl + "student/listMicroAndNano",
    isprevious: environment.baseUrl + "student/isprevious",
    listPriviousYearClass:environment.baseUrl + "student/listPriviousYearClass",
    listPreviousSubjects:environment.baseUrl + "student/listPreviousSubjects",
    getNotification:environment.baseUrl + "student/getNotification",
    listUnitWithChapter:environment.baseUrl + "student/listUnitWithChapter",
    listConcepts:environment.baseUrl + "student/listConcepts",
    listPreviewTopicsStudent:environment.baseUrl + "student/listPreviewTopics",
    listBatchStudentAPI: environment.baseUrl + "student/listBatch",
    enterBatchStudent: environment.baseUrl + "student/enterBatch",
    joinedUseCodeStudent: environment.baseUrl + "student/joinedUseCode",
    listTaskwithStudentsTask: environment.baseUrl + "student/listTaskwithStudentTask",

    //parent APIs
    getStudentListForParentAPI: environment.baseUrl + "parent/getStudents",
    getSubjectListForParentAPI: environment.baseUrl + "parent/listSubjects",
    getLessonListForParentAPI: environment.baseUrl + "parent/listLessons",
    getStudentReportsForParentAPI: environment.baseUrl + "parent/getStudentReports",
    getParentEvent : environment.baseUrl + "parent/getEvent",

    //cm APIs
    addDigitalSkillsAPI: environment.baseUrl + "digitalskill/addDigitalSkill",
    listDigitalSkillAPI: environment.baseUrl + "digitalskill/listDigitalSkill",
    updateDigitalSkillContent: environment.baseUrl + "digitalskill/addDigitalContent",
    listDigitalSkillContent: environment.baseUrl + "digitalskill/listDigitalSkillContent",
    getDigitalSkillContent: environment.baseUrl + "digitalSkill/getDigitalContent",
    getDigitalSkillDetails: environment.baseUrl + "digitalSkill/getDigitalSkill",
    
    


    //principal APIs
    principal: {
    getprincipalEvent: environment.baseUrl + "principal/getEvent",
    getCountAboutSchool: environment.baseUrl + "principal/getCountAboutSchool",
    getSectionLists: environment.baseUrl + "principal/listSection",
    getSectionWiseClasses: environment.baseUrl + "principal/listClasses",
    getSubejcts: environment.baseUrl + "principal/listSubject_Teacher",
    getLessons: environment.baseUrl + "principal/listLessons",
    getContents: environment.baseUrl + "principal/listContent",
    getSupportedLesson: environment.baseUrl + "principal/getSupportLesson",
    getStudentReports: environment.baseUrl + "principal/getStudentReports",
    monthlyBestTeacher: environment.baseUrl + "principal/monthlyBestTeacher",
    monthlyBestStudent: environment.baseUrl + "principal/monthlyBestStudent",
    listUnitPrincipal:environment.baseUrl + "principal/listUnit",
    listChapterinUnitPrincipal:environment.baseUrl + "principal/listChapterinUnit",
    listPreviewTopicsPrincipal:environment.baseUrl + "principal/listPreviewTopics",
    listMicroAndNanoPrincipal: environment.baseUrl + "principal/listMicroAndNano",
    listPreviewConceptsPrincipal:environment.baseUrl + "principal/listPreviewConcepts",
    listContentPrincipalAPI: environment.baseUrl + "principal/listContent",
    },

    //lab
    createLabLesson:environment.baseUrl + "lab/createLabLesson",
    listLesson: environment.baseUrl + "lab/listLesson",
    createInventory: environment.baseUrl + "lab/createInventory",
    listInventoryContent: environment.baseUrl + "lab/listInventoryContent",
    listInventory: environment.baseUrl + "lab/listInventory",
    createChallenge: environment.baseUrl + "lab/createChallenge",
    createTask: environment.baseUrl + "lab/createTask",
    listTask:environment.baseUrl + "lab/listTask",
    listfeedback:environment.baseUrl + "lab/listfeedback",
    reviewFeedback:environment.baseUrl + "lab/reviewFeedback",
    listSchool: environment.baseUrl + "lab/listSchool",
    listTeachersOfSchool: environment.baseUrl + "lab/listTeachersOfSchool",
    assignLevels: environment.baseUrl + "lab/assignLevels",
    listLevelUpTeachers: environment.baseUrl + "lab/listLevelUpTeachers",
    createBatch: environment.baseUrl + "lab/createBatch",
    listBatch: environment.baseUrl + "lab/listBatch",
    
}


export default APIStandars;